### ISSUE TITLE
Better environment management

### ISSUE THREAD

**Issue by jopereyral** [joamadorrr/librarian-meeseeks#1]
Hi 🥇 

I just see your repo, I'm not sure what you want to accomplish but I can help you with your environment properties if you explain me what you need :) also with installation guide using virtualenv 💪

**Comment by joamadorrr** [comment]
> Hi 
> 
> I just see your repo, I'm not sure what you want to accomplish but I can help you with your environment properties if you explain me what you need :) also with installation guide using virtualenv

I'm working on that rn, if you wanna help with something else I'll be listing a few issues I wanna address soon, so you can pick from there if you want :)
